run:
	cp --f ./reflector.py ./reflector
	python3 ./reflector --interface eth0 --victim-ip 192.168.1.10 --victim-ethernet 31:16:A9:63:FF:83 --reflector-ip 192.168.1.20 --reflector-ethernet 38:45:E3:89:B5:56
	chmod +x ./reflector
	
